### ISSUE TITLE
Building a changeset from 'belongs-to' association (question)

### ISSUE THREAD

**Issue by arturocadena** [DockYard/ember-changeset#127]
Hi, 

I'd like to know if this is posible. I want to create a changeset from a belongs-to association. I have a User model associated to one Location. So, in my template I wrote this:

{{location-form changeset=(changeset model.location)}}

but that doesn't build the changeset properly.

Thanks.

**Comment by poteto** [comment]
What do you mean by doesn't build the changeset properly?

**Comment by arturocadena** [comment]
Sorry for the poor explanation. Specifically, when I call the method `save()` on the changeset object in my controller, nothing happens . Following a similar pattern as the documentation, I have something like this:

My two models

```javascript
// app/models/user.js
import DS from 'ember-data';

export default DS.Model.extend({
  // others attributes omitted
  location: DS.belongsTo('location')
});
```

```javascript
// app/models/location.js
import DS from 'ember-data';

export default DS.Model.extend({
  // other attributes omitted
  user: DS.belongsTo('user')
});
```

I load the user in a parent route

```javascript
// app/routes/users/edit.js
import Ember from 'ember';

export default Ember.Route.extend({
  model(params) {
    return this.get('store').findRecord('user', params.user_id);
  }
});
```

Then, I use the changeset helper passing the user's location

```handlebars
<!-- app/templates/users/edit/location.hbs -->
{{location-form
    changeset=(changeset model.location)
    submit=(action 'submit')
    rollback=(action 'rollback')
}}
``` 

```handlebars
<!-- app/templates/components/location-form.hbs -->
<!-- rest of the form omitted -->
<button {{action submit changeset}} type='submit'>
  Update
</button>
```

Finally,  my controller

```javascript
// app/controllers/users/edit/location.js
import Ember from 'ember';

export default Ember.Controller.extend({
  actions: {
    submit(changeset) {
      changeset.save(); // This does nothing :(
    },

    rollback(changeset) {
      changeset.rollback();
    }
  }
});
```

This is because `model.location` returns a promise and the changeset helper doesn't expect that?

Thanks (:

**Comment by poteto** [comment]
Ah I see. For now, would this work?

```js
// app/controllers/users/edit/location.js
import Ember from 'ember';

const { Controller, computed: { alias } } = Ember;

export default Controller.extend({
  location: alias('user.location')
});
```

```hbs
<!-- app/templates/users/edit/location.hbs -->
{{location-form
    changeset=(changeset location)
    submit=(action 'submit')
    rollback=(action 'rollback')
}}
```

**Comment by fotinakis** [comment]
I might have more information on this bug, I think the bug is that `save()` delegation through to the model doesn't quite work when the changeset model is a `DS.PromiseObject` (which might happen if it's an async belongsTo).

For example, I hit this when I did:
```javascript
let changeset = new Changeset(model, lookupValidator(validator), validator);
```
And `model` was passed via a template, like:
```javascript
{{my-form model=post.author}}
```
...where `author` is an async belongsTo relationship on the `post` model. The behavior I saw in the Ember Inspector after `save()` was that the model would be dirty and would have the attribute updated, but would _not_ ever actually save the model and no network request was ever made. I'm not sure what ember-data does if you try to `.save()` a `DS.PromiseObject`.

**Comment by poteto** [comment]
Hmm, I'm unsure if a `changeset` should know about `DS.PromiseObject`. What if you resolved the promise prior to creating it?

```js
get(model, 'location').then((location) => set(this, 'changeset', new Changeset(/* ... */);
```

**Comment by poteto** [comment]
I suppose this makes for a poor experience though. I'll most likely update changeset so it can resolve a promise if one is passed into it as a model.

**Comment by poteto** [comment]
Can you give https://github.com/DockYard/ember-changeset/pull/130 or https://github.com/DockYard/ember-changeset-validations/pull/106 a try and see if it works for you?

**Comment by arturocadena** [comment]
I will try this tomorrow. Thank you!

**Comment by arturocadena** [comment]
Hi @poteto, 

I tried to use your patch but I'm not sure if I did it well. I wrote this in my package.json:

```javascript
 "devDependencies": {
    "ember-changeset": "DockYard/ember-changeset#pull/130/head",
    "ember-changeset-validations": "DockYard/ember-changeset-validations#pull/106/head",
}
```
Then, after remove the old node_modules and reinstall them, my 'use case' still doesn't work. But, again, I'm not sure if this is the right way to use your patch.

I also tried with commit ids in the package.json.

**Comment by poteto** [comment]
Try

```js
"devDependencies": {
    "ember-changeset": "DockYard/ember-changeset#8780f451b266cfb210e793780df2bec8cdc6852e",
    "ember-changeset-validations": "DockYard/ember-changeset-validations#ba4063bbd16e0d4933ad506728364dde3e16afdf",
}
```

Can you also please `console.log` the `changeset` variable in your `submit` action?

```js
submit(changeset) {
  console.log(changeset);
}
```

**Comment by gmarkv10** [comment]
Hello all, I have also bumped up against this issue in the last week and might have a little more insight to offer. I am using your package as follows:

I have my validations file imported into the route, I pass it into a dialog in the route's template we use to create new MyModel object so it looks like:

`{{create-dialog
...
mymodel=(changeset model.myModel model.mymodelvalidations) relatedModels=model.relatedModels
... }}
`
The create-dialog has a Save button, leading to a save action which operates like this:

`onSave(){

			this.mymodel.validate();

			if(this.mymodel.get('errors.length')){

				this.get('mymodel.errors').forEach( (err) => {

					this.notifications.error(`${err.validation[0]}`);

				});

			} else {

				this.mymodel.execute();

				Ember.run.schedule('actions', this, function() {

					this.sendAction('onSave', this.mymodel); 

				});

			}

		},`

The problem, as discussed above us that properties of mymodel **that are relations** (they are set with dropdowns and other components further down the component chain) are represented in the changes array in onSave() but are not present in the actual this.mymodel after calling changesets save() or in this case, execute(). (Non-related fields are set just fine)

After some static debugging, it appears that ember-changset uses Ember's own setProperties method, and this seems to get tripped up by setting relations. This is in spite of retrieving the models that I want to set as related properties alongside mymodel in an RSVP hash on the route on top of all these components (notice them being passed into the create-dialog component in my first code snippet).  

Handling async belongs-To relationships should be considered alongside this inconsistent behavior, which again, I think is caused by not deviating from using Ember.setProperties to set all changes in your changesets, even complex relationships.

**Comment by arturocadena** [comment]
`console.log`output
```
DEBUG: -------------------------------
DEBUG: Ember             : 2.7.3
DEBUG: Ember Data        : 2.9.0
DEBUG: jQuery            : 2.2.4
DEBUG: -------------------------------
Promise
    __ember_meta__: Meta
    _id: 161
    _label: undefined
    _result: Class
        __ember1478548228545: null
        __ember_meta__: Meta
             _bindings: undefined
             _cache: undefined
             _chainWatchers: undefined
             _chains: ChainNode
             _deps: undefined
             _listeners: undefined
             _listenersFinalized: undefined
             _mixins: undefined
             _suspendedListeners: undefined
             _tag: undefined
             _values: undefined
             _watching: undefined
             _weak: undefined
             parent: Meta
             proto: undefined
             source: Class
             __proto__: Object
    _changes: Object
    _content: Class
    _errors: Object
    _super: ROOT()
    _validator: defaultValidatorFn()
    __proto__: Class_state: 1
    _subscribers: Array[0]
    __proto__: Object
```

**Comment by karellm** [comment]
Is there any update on this? I actually ran into exactly this issue. I'd love to know if there is a fix or preferred way to handle this. Thanks!

**Comment by mfazekas** [comment]
So for this example:

```hbs
{{location-form
    changeset=(changeset user.location)
    submit=(action 'submit')
    rollback=(action 'rollback')
}}
```

the issue is that `user.location` is an [PromiseObject](http://emberjs.com/api/data/classes/DS.PromiseObject.html) and it's not fully supported by changeset, i think the cleanest solution is something like this:

```hbs
{{#if  user.location. isFulfilled}}
{{location-form
    changeset=(changeset user.location.content)
    submit=(action 'submit')
    rollback=(action 'rollback')
}}
{{else}}
Loading data...
{{/if}}
```

**Comment by rwwagner90** [comment]
I still seem to be hitting this issue 😞
