### ISSUE TITLE
Question: What is validationMap?

### ISSUE THREAD

**Issue by ivanvanderbyl** [DockYard/ember-changeset#76]
In the method signature for `changeset(obj, validateFn = defaultValidatorFn, validationMap = {})`, what is the purpose of `validationMap` and why is it not documented?

**Comment by dustinfarris** [comment]
A validation map is a POJO that maps your attributes to one or more validators.

See documentation in [ember-changeset-validations README](https://github.com/DockYard/ember-changeset-validations/blob/master/README.md)

**Comment by poteto** [comment]
Yeah it should be documented, I'll make an update

**Comment by gjastrab** [comment]
Also some clearer documentation on how to instantiate a changeset directly in a component JS file instead of only in a template would be good. I was playing around with this to try to understand it better and was wondering why my changeset with a blank value on `name` was not coming back as invalid within the validate() promise:

`app/validators/foo.js` just having a simple presence validator like:
```
export default {
  name: validatePresence(true)
}
```

when the changeset was being instantiated in a component's `didReceiveAttrs` like:

```
import Changeset from 'ember-changeset';
import FooValidations from 'foo/validators/foo';

export default Ember.Component.extend({
  didReceiveAttrs() {
    this._super(...arguments);
    this.set('changeset', new Changeset(this.get('model'), FooValidations));
  }
})
```

It wouldn't work until I perused through  [e-c-v's helper source](https://github.com/DockYard/ember-changeset-validations/blob/master/addon/helpers/changeset.js#L10) and changed it to be:

```
import Changeset from 'ember-changeset';
import FooValidations from 'foo/validators/foo';
import lookupValidator from 'ember-changeset-validations';

export default Ember.Component.extend({
  didReceiveAttrs() {
    this._super(...arguments);
    this.set('changeset', new Changeset(this.get('model'), lookupValidator(FooValidations), FooValidations));
  }
})
```

I'd guess using the `changeset` helper in templates will be the more trodden path but especially reading [your blog post](https://emberway.io/bringing-ecto-changesets-into-ember-js-8e665ec70ab6) introducing this and seeing the simple case introduced as a simple

```
let changesetA = new Changeset(user, validatorFn);
```

It took a bit of trial and error for me to figure this. Is directly using `lookupValidator` as I did above the cleanest way to use this in a non-template situation?

Thanks!
